// [city] Real ground-floor (and stacked upper-floor) tenants along the streets round the scramble, 2025–2026, by
// position (game metres, compressed like the map). Filled from OSM + store pages / street surveys (see
// docs/reports/city.md, pass 11); brands carry their NAMES.md near-names. genericBuilding.js gives each infill
// shop bay the nearest unused entry within a few metres (its name on the fascia, its interior type), and the 2F
// tenant board the nearest upper-floor entry.
//   { street, side, pos: [x, z], name, cat, floor }   cat → interior type via TENANT_TYPE
// (pass 15: the 道玄坂 corridor's rows — true metres — come from dogenzakaData.js DOGEN_SHOPS, appended at the end)
import { DOGEN_SHOPS } from '../dogenzakaData.js';
export const SHOP_TENANTS = [
  {"street":"center","side":"N","pos":[-25.6,-34.7],"name":"SHIBUYA TSUTAYU (Q-FRONT)","cat":"books","floor":1},
  {"street":"center","side":"N","pos":[-25.6,-34.7],"name":"STARBEANS COFFEE","cat":"cafe","floor":2},
  {"street":"center","side":"N","pos":[-35.1,-45.3],"name":"GASPANIK","cat":"izakaya","floor":1},
  {"street":"center","side":"N","pos":[-37.2,-47.7],"name":"山上本気うどん","cat":"ramen","floor":1},
  {"street":"center","side":"N","pos":[-39.7,-50.6],"name":"横浜家系ラーメン 壹角家","cat":"ramen","floor":1},
  {"street":"center","side":"N","pos":[-42.9,-53.5],"name":"超俺流汐ラーメン","cat":"ramen","floor":1},
  {"street":"center","side":"N","pos":[-49.6,-59.5],"name":"ビックエコー","cat":"karaoke","floor":1},
  {"street":"center","side":"N","pos":[-55.7,-65],"name":"#C-plu","cat":"game","floor":1},
  {"street":"center","side":"N","pos":[-59.3,-68.2],"name":"mineco","cat":"other","floor":1},
  {"street":"center","side":"N","pos":[-72.2,-73.3],"name":"チュチュアンヌ","cat":"fashion","floor":1},
  {"street":"center","side":"N","pos":[-72.2,-73.3],"name":"ACCIA","cat":"other","floor":3},
  {"street":"center","side":"N","pos":[-80.6,-74.9],"name":"OOKURA","cat":"other","floor":1},
  {"street":"center","side":"N","pos":[-103.8,-79.7],"name":"らーめん金殿丸","cat":"ramen","floor":1},
  {"street":"center","side":"N","pos":[-103.8,-79.7],"name":"北海道らーめん おくむろ","cat":"ramen","floor":2},
  {"street":"center","side":"N","pos":[-110.5,-81.3],"name":"Pandara","cat":"other","floor":1},
  {"street":"center","side":"N","pos":[-123.4,-86.8],"name":"揚國福マーラータン","cat":"ramen","floor":1},
  {"street":"center","side":"N","pos":[-125.8,-87.9],"name":"野朗ラーメン","cat":"ramen","floor":1},
  {"street":"center","side":"N","pos":[-125.8,-87.9],"name":"喫茶室ルノアーレ","cat":"cafe","floor":2},
  {"street":"center","side":"N","pos":[-137.8,-92.9],"name":"ファミリマート","cat":"conv","floor":1},
  {"street":"center","side":"N","pos":[-137.8,-92.9],"name":"椿家カフェ","cat":"cafe","floor":3},
  {"street":"center","side":"N","pos":[-148.6,-97.3],"name":"バーガーキンク (BURGER KINC)","cat":"fast","floor":1},
  {"street":"center","side":"N","pos":[-148.6,-97.3],"name":"一件め酒場","cat":"izakaya","floor":3},
  {"street":"center","side":"N","pos":[-160.4,-102.2],"name":"atomos pink","cat":"bank","floor":1},
  {"street":"center","side":"N","pos":[-166.4,-104.8],"name":"カラオケ舘 渋谷本店","cat":"karaoke","floor":1},
  {"street":"center","side":"N","pos":[-181.6,-113.6],"name":"マモケバプ","cat":"fast","floor":1},
  {"street":"center","side":"N","pos":[-181.6,-113.6],"name":"カラオケBonBon 2号店","cat":"karaoke","floor":6},
  {"street":"center","side":"N","pos":[-190.6,-121.3],"name":"カプセル楽曲","cat":"game","floor":1},
  {"street":"center","side":"N","pos":[-192.3,-122.7],"name":"モーセスさんのケバブ","cat":"fast","floor":1},
  {"street":"center","side":"N","pos":[-195.4,-125.2],"name":"GiGU 渋谷","cat":"game","floor":1},
  {"street":"center","side":"N","pos":[-195.4,-125.2],"name":"カラオケまねきねご","cat":"karaoke","floor":6},
  {"street":"center","side":"N","pos":[-195.9,-125.9],"name":"どうとんぼり神坐","cat":"ramen","floor":1},
  {"street":"center","side":"N","pos":[-200.8,-133.1],"name":"牛かつもと林","cat":"other","floor":1},
  {"street":"center","side":"N","pos":[-200.8,-133.1],"name":"yoI","cat":"izakaya","floor":3},
  {"street":"center","side":"N","pos":[-204.3,-138.3],"name":"セアブラノ紳","cat":"ramen","floor":1},
  {"street":"center","side":"N","pos":[-204.3,-138.3],"name":"渋谷ギョーザ","cat":"other","floor":2},
  {"street":"center","side":"N","pos":[-208.2,-144],"name":"小肥洋 LITTLE SHEEPS","cat":"other","floor":1},
  {"street":"center","side":"N","pos":[-208.2,-144],"name":"THE ALDGAIT","cat":"izakaya","floor":3},
  {"street":"center","side":"N","pos":[-208.2,-144],"name":"礒丸水産","cat":"izakaya","floor":1},
  {"street":"center","side":"N","pos":[-208.2,-144],"name":"焼き鳥 采","cat":"izakaya","floor":3},
  {"street":"center","side":"S","pos":[-41.6,-31.3],"name":"三千里薬局","cat":"drug","floor":1},
  {"street":"center","side":"S","pos":[-41.6,-31.3],"name":"牛繋","cat":"other","floor":3},
  {"street":"center","side":"S","pos":[-56.3,-46.8],"name":"シブヤエンジェルハート","cat":"other","floor":1},
  {"street":"center","side":"S","pos":[-56.3,-46.8],"name":"渋谷西林フルーツパーラー","cat":"cafe","floor":2},
  {"street":"center","side":"S","pos":[-64.9,-54.4],"name":"鳥通酒場","cat":"izakaya","floor":1},
  {"street":"center","side":"S","pos":[-79.9,-60.5],"name":"ヴィレッジヴァンガート","cat":"books","floor":1},
  {"street":"center","side":"S","pos":[-82.5,-61],"name":"ジュエリーツヅミ","cat":"other","floor":1},
  {"street":"center","side":"S","pos":[-82.5,-61],"name":"鳥さんまい","cat":"izakaya","floor":4},
  {"street":"center","side":"S","pos":[-95,-63.3],"name":"SUMADOLI-BAR","cat":"izakaya","floor":1},
  {"street":"center","side":"S","pos":[-100.6,-64.4],"name":"BRAND OF SHIBUYA","cat":"other","floor":1},
  {"street":"center","side":"S","pos":[-100.6,-64.4],"name":"Rodeo Drlve","cat":"fashion","floor":5},
  {"street":"center","side":"S","pos":[-105.1,-65.6],"name":"ABC-MARK GRAND STAGE","cat":"shoes","floor":1},
  {"street":"center","side":"S","pos":[-143.8,-80.2],"name":"松家","cat":"fast","floor":1},
  {"street":"center","side":"S","pos":[-143.8,-80.2],"name":"りらっくる","cat":"other","floor":2},
  {"street":"center","side":"S","pos":[-154.4,-84.6],"name":"マイアミガーデナ","cat":"other","floor":1},
  {"street":"center","side":"S","pos":[-154.4,-84.6],"name":"カラオケ歌廣場 別館","cat":"karaoke","floor":2},
  {"street":"center","side":"S","pos":[-164.6,-88.8],"name":"桂華ラーメン","cat":"ramen","floor":1},
  {"street":"center","side":"S","pos":[-173.5,-92.6],"name":"ABC-MARK","cat":"shoes","floor":1},
  {"street":"center","side":"S","pos":[-173.5,-92.6],"name":"カラオケ歌廣場 本館","cat":"karaoke","floor":5},
  {"street":"center","side":"S","pos":[-186.5,-99.3],"name":"威凰","cat":"ramen","floor":1},
  {"street":"center","side":"S","pos":[-186.5,-99.3],"name":"海鮮浜焼酒場 トロハナ","cat":"izakaya","floor":2},
  {"street":"center","side":"S","pos":[-190.6,-102.9],"name":"マックドナルド","cat":"fast","floor":1},
  {"street":"center","side":"S","pos":[-190.6,-102.9],"name":"青竜門","cat":"izakaya","floor":4},
  {"street":"center","side":"S","pos":[-209.9,-121.6],"name":"アジアの昧","cat":"other","floor":1},
  {"street":"center","side":"S","pos":[-216.8,-131.7],"name":"Zolf","cat":"fashion","floor":1},
  {"street":"center","side":"S","pos":[-216.8,-131.7],"name":"富士嘉商店","cat":"izakaya","floor":2},
  {"street":"scramble","side":"NW","pos":[-14.9,-43.3],"name":"Q-FRONT","cat":"books","floor":1},
  {"street":"scramble","side":"N","pos":[-27.6,-89],"name":"西部渋谷店 (SEIBO) A館","cat":"other","floor":1},
  {"street":"scramble","side":"NE","pos":[21.3,-32.4],"name":"MAGNET by SHIBUYA1O9","cat":"other","floor":1},
  {"street":"scramble","side":"NE","pos":[21.3,-32.4],"name":"星野珈琲店","cat":"cafe","floor":2},
  {"street":"scramble","side":"SW","pos":[-46.4,24],"name":"サンドラック","cat":"drug","floor":1},
  {"street":"scramble","side":"SW","pos":[-46.4,24],"name":"ロクシタヌカフェ (L'OCCITANO CAFE)","cat":"cafe","floor":3},
  {"street":"scramble","side":"W","pos":[-63,-26.5],"name":"渋谷西林フルーツ","cat":"other","floor":1},
  {"street":"scramble","side":"W","pos":[-71.2,-33.3],"name":"マツモトキヨヒ SHIBUYA SCRAMBLE FLAG","cat":"drug","floor":1},
  {"street":"scramble","side":"W","pos":[-37.9,-29.5],"name":"大成堂書店","cat":"books","floor":1},
  {"street":"scramble","side":"W","pos":[-37.9,-29.5],"name":"牛繋","cat":"other","floor":3},
  {"street":"koen","side":"E","pos":[16.5,-33.9],"name":"MAGNET by SHIBUYA1O9","cat":"other","floor":1},
  {"street":"koen","side":"E","pos":[26.2,-76.3],"name":"MOM'Z TOUCH","cat":"fast","floor":1},
  {"street":"koen","side":"E","pos":[29,-92.6],"name":"太和証券","cat":"bank","floor":1},
  {"street":"koen","side":"E","pos":[30,-116],"name":"三井往友信託銀行","cat":"bank","floor":1},
  {"street":"koen","side":"E","pos":[30,-117.8],"name":"HOCA Shibuya","cat":"shoes","floor":1},
  {"street":"koen","side":"E","pos":[30,-133.9],"name":"ZAPA","cat":"fashion","floor":1},
  {"street":"koen","side":"E","pos":[30,-162.4],"name":"一乱","cat":"ramen","floor":1},
  {"street":"koen","side":"E","pos":[30,-169.9],"name":"ファミリマート","cat":"conv","floor":1},
  {"street":"koen","side":"E","pos":[30,-176.4],"name":"カラオケパセロ","cat":"karaoke","floor":1},
  {"street":"koen","side":"E","pos":[30,-204.7],"name":"TOWER RECORD 渋谷","cat":"books","floor":1},
  {"street":"koen","side":"N","pos":[-8.7,-178.5],"name":"MOD1 - Onitsuka Tigar","cat":"other","floor":1},
  {"street":"koen","side":"N","pos":[-8.7,-178.5],"name":"HNV&BOOKS","cat":"books","floor":7},
  {"street":"koen","side":"N","pos":[-39.4,-190.7],"name":"楽電モバイル","cat":"cafe","floor":1},
  {"street":"koen","side":"N","pos":[-44.1,-193.4],"name":"大戸家","cat":"other","floor":1},
  {"street":"koen","side":"N","pos":[-49.1,-195.1],"name":"BIRKENSTOK","cat":"shoes","floor":1},
  {"street":"koen","side":"N","pos":[-61.5,-200.1],"name":"Chacot","cat":"fashion","floor":1},
  {"street":"koen","side":"N","pos":[-71.2,-204.3],"name":"Appel Store","cat":"elec","floor":1},
  {"street":"koen","side":"N","pos":[-80.9,-208.9],"name":"オーマイグラズ東京","cat":"drug","floor":1},
  {"street":"koen","side":"N","pos":[-90.8,-214.6],"name":"JOURNAL STANDART FURNITURE","cat":"other","floor":1},
  {"street":"koen","side":"N","pos":[-90.6,-214.5],"name":"Ray-Bam SHIBUYA","cat":"other","floor":1},
  {"street":"koen","side":"N","pos":[-97.7,-219.1],"name":"エクセルシオーレ カフェ","cat":"cafe","floor":1},
  {"street":"koen","side":"N","pos":[-108.1,-228.4],"name":"(as-is, public)","cat":"other","floor":1},
  {"street":"koen","side":"S","pos":[-2.2,-161.8],"name":"NYKE Shibuya","cat":"shoes","floor":1},
  {"street":"koen","side":"S","pos":[-25.7,-171.4],"name":"Dizney store","cat":"other","floor":1},
  {"street":"koen","side":"S","pos":[-25.7,-171.4],"name":"バルバッコラ","cat":"other","floor":6},
  {"street":"koen","side":"S","pos":[-40.8,-176.9],"name":"北参堂 COFFEE Lab.","cat":"cafe","floor":1},
  {"street":"koen","side":"S","pos":[-64.4,-186.7],"name":"西部 モヴィーダ館 (無地良品)","cat":"other","floor":1},
  {"street":"koen","side":"S","pos":[-87.4,-197],"name":"(as-is)","cat":"other","floor":1},
  {"street":"koen","side":"S","pos":[-117.8,-220.2],"name":"渋谷PALCO","cat":"fashion","floor":1},
  {"street":"koen","side":"S","pos":[-117.8,-220.2],"name":"Nintendoo TOKYO","cat":"game","floor":6},
  {"street":"koen","side":"W","pos":[1,-30.9],"name":"STARBEANS COFFEE","cat":"cafe","floor":1},
  {"street":"koen","side":"W","pos":[12.4,-78.9],"name":"西部渋谷店 A館","cat":"other","floor":1},
  {"street":"koen","side":"W","pos":[16,-128],"name":"西部渋谷店 B館","cat":"other","floor":1},
  {"street":"koen","side":"W","pos":[16,-138.6],"name":"Olivo LOUNGE (SNBC + STARBEANS)","cat":"bank","floor":1},
  {"street":"koen","side":"W","pos":[16,-151.7],"name":"眼鏡市揚","cat":"other","floor":1},
  {"street":"inokashira","side":"E","pos":[-206.4,-182.6],"name":"サンマルコカフェ","cat":"cafe","floor":1},
  {"street":"inokashira","side":"E","pos":[-206.4,-182.6],"name":"温野采","cat":"other","floor":2},
  {"street":"inokashira","side":"E","pos":[-207.7,-182.7],"name":"U.F.O. by Francfrank","cat":"other","floor":1},
  {"street":"inokashira","side":"E","pos":[-207.7,-182.7],"name":"Shake Shock","cat":"fast","floor":2},
  {"street":"inokashira","side":"E","pos":[-213,-193.8],"name":"じゃんぱる","cat":"elec","floor":1},
  {"street":"inokashira","side":"E","pos":[-213.8,-208.3],"name":"ハンド 渋谷店","cat":"other","floor":1},
  {"street":"inokashira","side":"N","pos":[-10.7,-118.5],"name":"西部渋谷店 B館","cat":"other","floor":1},
  {"street":"inokashira","side":"N","pos":[-85.6,-136.7],"name":"LOFTY","cat":"other","floor":1},
  {"street":"inokashira","side":"N","pos":[-94.8,-138.2],"name":"PRONTE","cat":"cafe","floor":1},
  {"street":"inokashira","side":"N","pos":[-125.1,-142.8],"name":"CHARLIES & KEITH","cat":"fashion","floor":1},
  {"street":"inokashira","side":"N","pos":[-143.5,-145.5],"name":"RANDO","cat":"shoes","floor":1},
  {"street":"inokashira","side":"N","pos":[-156.3,-149],"name":"KOMEHYU SHIBUYA","cat":"other","floor":1},
  {"street":"inokashira","side":"N","pos":[-177.5,-154.4],"name":"マツモトキヨヒ","cat":"drug","floor":1},
  {"street":"inokashira","side":"N","pos":[-177.5,-154.4],"name":"ポムの横","cat":"other","floor":2},
  {"street":"inokashira","side":"N","pos":[-189.8,-158.2],"name":"ちとせ会舘 (ムラサギスポーツ)","cat":"fashion","floor":1},
  {"street":"inokashira","side":"N","pos":[-189.8,-158.2],"name":"渋谷肉横町","cat":"other","floor":3},
  {"street":"inokashira","side":"S","pos":[-9.2,-104],"name":"西部渋谷店 A館","cat":"other","floor":1},
  {"street":"inokashira","side":"S","pos":[-55.7,-114.9],"name":"IKEYA 渋谷","cat":"other","floor":1},
  {"street":"inokashira","side":"S","pos":[-55.7,-114.9],"name":"スウェーデソレストラン","cat":"other","floor":7},
  {"street":"inokashira","side":"S","pos":[-90.5,-123.3],"name":"ヨコダ薬局","cat":"drug","floor":1},
  {"street":"inokashira","side":"S","pos":[-94.8,-124],"name":"日本油堂","cat":"ramen","floor":1},
  {"street":"inokashira","side":"S","pos":[-109.8,-126.4],"name":"エクセルシオーレ カフェ","cat":"cafe","floor":1},
  {"street":"inokashira","side":"S","pos":[-120.7,-128],"name":"ZAPA","cat":"fashion","floor":1},
  {"street":"inokashira","side":"S","pos":[-148.1,-132.1],"name":"SKETCHERS","cat":"shoes","floor":1},
  {"street":"inokashira","side":"S","pos":[-154.5,-133.8],"name":"The Bodi Shop","cat":"drug","floor":1},
  {"street":"inokashira","side":"S","pos":[-155.7,-134.1],"name":"HUBB 2号店","cat":"izakaya","floor":1},
  {"street":"inokashira","side":"S","pos":[-169.1,-140.2],"name":"元組寿司","cat":"ramen","floor":1},
  {"street":"inokashira","side":"S","pos":[-169.1,-140.2],"name":"ふだご","cat":"family","floor":2},
  {"street":"inokashira","side":"S","pos":[-175.8,-142.7],"name":"Swotch","cat":"other","floor":1},
  {"street":"inokashira","side":"S","pos":[-188.9,-147.2],"name":"カラオケまねきねご","cat":"karaoke","floor":6},
  {"street":"inokashira","side":"S","pos":[-196.4,-150.4],"name":"新時伐","cat":"izakaya","floor":1},
  {"street":"inokashira","side":"S","pos":[-196.4,-150.4],"name":"タルタルNUNA","cat":"other","floor":2},
  {"street":"inokashira","side":"S","pos":[-199.5,-153.1],"name":"カラオケ舘","cat":"karaoke","floor":1},
  {"street":"inokashira","side":"S","pos":[-203.5,-156.6],"name":"ディスクユニヨン","cat":"other","floor":1},
  {"street":"inokashira","side":"S","pos":[-203.5,-156.6],"name":"プンクム","cat":"other","floor":2},
  {"street":"inokashira","side":"W","pos":[-207,-161.9],"name":"ファミリマート","cat":"conv","floor":1},
  {"street":"inokashira","side":"W","pos":[-207,-161.9],"name":"VSlNG","cat":"karaoke","floor":2},
  {"street":"inokashira","side":"W","pos":[-207,-161.9],"name":"atomos","cat":"bank","floor":1},
  {"street":"inokashira","side":"W","pos":[-204.8,-167.2],"name":"味の中華 兆樂","cat":"other","floor":1},
  {"street":"inokashira","side":"W","pos":[-209.2,-166.1],"name":"らぁ麺 はやし由","cat":"ramen","floor":1},
  {"street":"inokashira","side":"W","pos":[-209.2,-166.1],"name":"午角","cat":"other","floor":2},
  {"street":"inokashira","side":"W","pos":[-211.8,-170.8],"name":"GO","cat":"fashion","floor":1},
  {"street":"inokashira","side":"W","pos":[-208.2,-172.8],"name":"焼肉ライフ","cat":"family","floor":1},
  {"street":"inokashira","side":"W","pos":[-208.2,-172.8],"name":"薄利多賣半平エ","cat":"izakaya","floor":2},
  {"street":"inokashira","side":"W","pos":[-209,-172.9],"name":"すき屋","cat":"fast","floor":1},
  {"street":"inokashira","side":"W","pos":[-210.6,-178.5],"name":"鳥通酒場","cat":"izakaya","floor":1},
  {"street":"inokashira","side":"W","pos":[-210.6,-178.5],"name":"鳥喜族","cat":"izakaya","floor":3},
  {"street":"inokashira","side":"W","pos":[-213.5,-184],"name":"渋谷BEAM (デッパーダン)","cat":"fast","floor":1},
  {"street":"inokashira","side":"W","pos":[-213.5,-184],"name":"イシハシ楽器","cat":"other","floor":2},
  {"street":"inokashira","side":"W","pos":[-216.4,-190.2],"name":"JlNS","cat":"fashion","floor":1},
  {"street":"inokashira","side":"W","pos":[-216.4,-190.2],"name":"R00TS","cat":"other","floor":3},
  {"street":"inokashira","side":"W","pos":[-221.2,-194.4],"name":"ドトーレ","cat":"cafe","floor":1},
  {"street":"inokashira","side":"W","pos":[-221.2,-194.4],"name":"麻雀オクタコン","cat":"other","floor":2},
  {"street":"inokashira","side":"W","pos":[-223.1,-205.2],"name":"スキ薬局","cat":"drug","floor":1},
  {"street":"inokashira","side":"W","pos":[-224.6,-210.2],"name":"HNV record shop","cat":"books","floor":1},
  {"street":"inokashira","side":"W","pos":[-224.6,-210.2],"name":"喫茶室ルノアーレ","cat":"cafe","floor":2},
  {"street":"bunkamura","side":"N","pos":[-114.3,-23.2],"name":"adidos Brand Center","cat":"fashion","floor":1},
  {"street":"bunkamura","side":"N","pos":[-135.8,-34.6],"name":"サーティウン ICE CREAM","cat":"fast","floor":1},
  {"street":"bunkamura","side":"N","pos":[-135.8,-34.6],"name":"不二屋レストラン","cat":"other","floor":2},
  {"street":"bunkamura","side":"N","pos":[-141.5,-37.2],"name":"まぜそば チョップズ","cat":"ramen","floor":1},
  {"street":"bunkamura","side":"N","pos":[-141.5,-37.2],"name":"まくろ漁業組合","cat":"izakaya","floor":3},
  {"street":"bunkamura","side":"N","pos":[-155.3,-43.5],"name":"ファミリマート","cat":"conv","floor":1},
  {"street":"bunkamura","side":"N","pos":[-155.3,-43.5],"name":"魚竜","cat":"izakaya","floor":2},
  {"street":"bunkamura","side":"N","pos":[-169,-49.7],"name":"しぶや駄果子バー","cat":"izakaya","floor":1},
  {"street":"bunkamura","side":"N","pos":[-169,-49.7],"name":"パンコントマチ","cat":"other","floor":2},
  {"street":"bunkamura","side":"N","pos":[-177.6,-54],"name":"メガネスーバー","cat":"other","floor":1},
  {"street":"bunkamura","side":"N","pos":[-185.5,-60.2],"name":"SoftBang 渋谷","cat":"other","floor":1},
  {"street":"bunkamura","side":"N","pos":[-200.9,-73.8],"name":"大黒家","cat":"other","floor":1},
  {"street":"bunkamura","side":"N","pos":[-202.1,-75.3],"name":"PRIZE SPOT PALU","cat":"game","floor":1},
  {"street":"bunkamura","side":"N","pos":[-202.1,-75.3],"name":"GROOVE","cat":"izakaya","floor":6},
  {"street":"bunkamura","side":"N","pos":[-202.5,-75.9],"name":"ドトーレ","cat":"cafe","floor":1},
  {"street":"bunkamura","side":"N","pos":[-202.5,-75.9],"name":"しゃぶしゃぶれだす","cat":"other","floor":2},
  {"street":"bunkamura","side":"N","pos":[-207.3,-82.1],"name":"三井往友銀行","cat":"bank","floor":1},
  {"street":"bunkamura","side":"N","pos":[-207.3,-82.1],"name":"SNBC信託銀行","cat":"bank","floor":3},
  {"street":"bunkamura","side":"N","pos":[-216.5,-94.8],"name":"MEGAドン・キホーヂ","cat":"other","floor":1},
  {"street":"bunkamura","side":"N","pos":[-220.3,-100],"name":"KOMEHYU 買取センター","cat":"bank","floor":1},
  {"street":"bunkamura","side":"S","pos":[-146.7,-24.2],"name":"SHIBUYA 1O9","cat":"fashion","floor":1},
  {"street":"bunkamura","side":"S","pos":[-200.8,-54.4],"name":"LABI ヤマド電機","cat":"elec","floor":1},
  {"street":"bunkamura","side":"S","pos":[-206.2,-58.6],"name":"洋服の青川","cat":"fashion","floor":1},
  {"street":"bunkamura","side":"S","pos":[-210.4,-63.2],"name":"Taco Bel","cat":"fast","floor":1},
  {"street":"bunkamura","side":"S","pos":[-211.7,-64.8],"name":"油そば ぶらぷら","cat":"ramen","floor":1},
  {"street":"bunkamura","side":"S","pos":[-218.1,-73.2],"name":"キリンシチー","cat":"izakaya","floor":1},
  {"street":"bunkamura","side":"S","pos":[-224.5,-81.9],"name":"道玄坂通 (Lil Woodie's","cat":"fast","floor":1},
  {"street":"bunkamura","side":"S","pos":[-229.3,-88.6],"name":"カラオケ舘","cat":"karaoke","floor":1},
  {"street":"bunkamura","side":"S","pos":[-231.7,-91.9],"name":"KEBAB CAFE","cat":"cafe","floor":1},
  {"street":"bunkamura","side":"S","pos":[-231.7,-91.9],"name":"カメラのキタムロ","cat":"elec","floor":1},
  ...DOGEN_SHOPS,
];
export const TENANT_TYPE = {
  drug: 'drug', conv: 'conv', fast: 'fast', cafe: 'cafe', izakaya: 'izakaya', ramen: 'ramen', karaoke: 'karaoke', game: 'game',
  pachi: 'pachi', fashion: 'fashion', shoes: 'fashion', sports: 'fashion', cosmetics: 'drug', elec: 'elec', books: 'books',
  bank: 'bank', '100yen': 'generic', other: 'generic', bar: 'bar', family: 'family', gyudon: 'ramen', restaurant: 'family',
};
